---
title: "CWSIS 2021 Narrative"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

CWSIS Narrative:  

# Project Focus and Rationale

“*The under-representation of people of color in science, technology, engineering, and mathematics STEM has become a crisis of significant proportion*” (Alfred et al., 2019, p. 114).

The purpose of this social impact scholarship project is to generate pilot data and proof of concepts for the Quantitative Methods in Education Research (QMER) learning community. This data will be used to seek federal funding [nsf grant]. This pilot data will be used as an empirical foundation for the grant proposal.
Include ROIs
The QMER learning community is …. And is being developed to fulfill the growing needs of Alabama citizens and our work addresses critical aspects of the Auburn University 2019-2024 Strategic Plan and the Big Four research commitments. Specifically, …

Innovative curriculum that supplements traditional statistical courses and builds pathways for integrating technological advances and teaching data science skills.
QMER will continue to provide opportunities for Auburn University students to participate in authentic and meaningful research in .. using big data … learning to use advanced technology …. and learn cutting edge data science skills, which will prepare students for modern careers. 
QMER will also continue to create an environment  to conduct transformative research that addresses critical issues faced by Alabama citizens, by 

The purpose of 
Increasing representation of women, students of color, first-generation, and low income students has been considered “critical to the nation’s progress” in developing a leading-edge STEM workforce (NSF, 2018, p. ii). It is well established that there are considerable disproportionalities in enrollment and persistence in STEM graduate programs, brought on by barriers including structural inequalities, limited mentorship opportunities, and cultural mismatch [CITE]. However, less attention has been paid to the ways in which institutional access contributes to these disparities. Historically underrepresented students (HUS) are infrequently exposed to the resources, support, and expertise in their postsecondary environments to enroll and persist in STEM programs (Austin, 2002). The institutional types most attended by HUS, such as HBCU, regional comprehensive, and community colleges often lack the capacity to support graduate students in STEM career development [CITE]

As a means to address disparities of institutional access and improve the STEM workforce in Alabama, the Quantitative Methods in Educational Research (QMER) group at Auburn University seeks to build a supportive and resource-rich quantitative and statistical skills learning community for a diverse array of students from HBCU, regional comprehensive, and community colleges in Alabama. We propose to overcome the gap between the type of postsecondary institution a student has access to, and the opportunity to be exposed to high-quality, STEM supportive learning environment and resources.

QMER is a research support group led by professors in the Department of Educational Foundations, Leadership, and Technology at Auburn. For the past 2 years, QMER has run an interdisciplinary learning community at Auburn to support and improve research and data skills central to STEM success. QMER has offered dozens of free workshops on topics including data management, coding, and statistical methods in a no risk, friendly, and open environment. This learning community has been intentionally designed around principals supportive of historically underrepresented students [CITE]. QMER also runs two research labs with a diverse and interdisciplinary team of students, focused on improving educational equity in Alabama through the use of an extensive collection of public-use data accessible on our own powerful server and networked computing hub. These labs offer students a chance to jump into research with diverse team of interested students, with all the data and computing resources provided. We believe the growth and success of our program at Auburn may be well-positioned to extended across institutional types to serve historically underrepresented students and address the social challenge of building a diverse STEM workforce in Alabama. 

However, there is still much we do not know about bridging the gap across institutional disparities and STEM success. Creating a long term and successful collaborations to address such disparities will require considerable research on student strengths and needs, curricular alignment, and modes of institutional fit. As such, we hope to pilot this institutional collaboration to gain insights on the following research questions: (1) Does a cross-institutional learning community improve student efficacy and confidence in STEM learning and skills? Does it address the barriers of historically underrepresented students, including cultural fit, sense of belonging, and need for mentorship? (2) What are the unique strengths and assets that historically underrepresented students bring to a learning community, and how can these best be engaged by the structure and approach of the learning environment? (3) What are the unique needs and strengths of non-research-intensive institutions creating inter-university STEM partnerships? 

Our goal is to extend our resources to foster collaborative partnerships with local colleges towards a STEM professional development pipeline to improve the strength and diversity of the STEM workforce in Alabama. It is part of our broader hopes to support the University mission to improve opportunities and quality of life for all Alabamians through “forward-thinking education,” and align with Auburn’s 2019-2024 Strategic Plan and “Big Four” research commitments to “create intelligent solutions” and “build resilient societies.” Our objectives are as follows: (1) To support HUS in STEM research skills through access to, and participation in, the QMER learning community and research teams. This includes ongoing learning community workshops on statistical and research skills, personal support from trained methodologists, access to software, and access to extensive data and computing resources; (2) To promote the strengths, assets, and perspectives of HUS in STEM curriculum design, and engage in iterative curricular development to support these students now and in the future; (3) To build, maintain, and scale research partnerships between Auburn and other Alabama colleges to improve student pathways and encourage equitable access to STEM through supportive research opportunities and resources. 

We believe if these objectives are successful, our impact will be to develop a new format of inter-university partnership that may (1) improve STEM diversity and research capability in Alabama; (2) remove barriers and support strengths for historically underrepresented students in STEM fields; (3) provide a scalable structure and curriculum for future programs; (4) promote increased visibility and prestige for Auburn University’s commitment to excellent research and outreach; (5) support readiness and recruitment for historically underrepresented student groups. 

We hope this research will lead to further development of learning community design, curriculum, and structure that may produce a series of publications and conference presentations on learning community design and inter-university partnerships for STEM diversification. We specifically intend to use the current project to build towards the research base and networks necessary to apply for future external grants. Specifically, the National Science Foundation’s EHR Core Research (ECR): Building Capacity in STEM Education Research Grant (ECR: BCSER). Ultimately, we hope to use that grant opportunity to extend our partnership model to K-12 schools to improve accessibility, diversification, and rigor of STEM research and learning in Alabama.

## Approach and Methodology

To gain a sense into the benefits of a cross-institutional learning community, our aim is to extend access to the QMER learning community and labs to a select set of students at local Alabama institutions through the development of working partnerships. These partnerships will include two community colleges: Southern Union Community College and Chattahoochee Valley Community College; and two HBCUs: Miles College and Stillman College. We will facilitate relationships with the social and natural sciences programs at each college, specifically targeting programs such as computer information systems, environmental science, mathematics, and the social sciences. 

To address our research questions, we propose four phases of project: (1) Partnership development; (2) student recruitment; (3) program execution; and (4) data collection and analysis.  

1.	*Partnership development*. Our first step is to reach out to programs and departments at each of the identified colleges to develop buy-in to the program. Here, we will approach each college department chair/head from the above-listed programs with our proposal and ask for interested faculty. We will establish regular meeting times with interested faculty, and state our intent to involve interested students in advanced data and statistical programming, as well as use faculty input to design our programming to better meet the unique needs of the college to promote STEM advancement.
2.	*Student recruitment*. Next, leveraging these partnerships, we will ask partner faculty to promote QMER workshops and labs, and may personally visit to promote if approved by the instructor. We will ask partner faculty to help identify students specifically who come from historically underrepresented student groups. Interested students will be asked to fill out a brief questionnaire on interests, career goals, goals for the QMER program, skills, and areas they want to know more about before attending. 
3.	*Program execution*. For a full [semester/year], QMER will host these students for our workshops and labs. Students will not be introduced based on their institution, but on their interests, as is the current practice with the QMER learning community. Students will be asked to attend 2 monthly workshops and two monthly research labs. The workshops will cover [introductions to statistical thinking, data analysis, data management, data visualization, R language, programming, reproducible research techniques, and statistical inference]. Lessons will evolve organically with student pacing and needs. The research labs will introduce students to an ongoing research project involving big data and educational equity specific to Alabama. Using a problem-based approach, students will be asked to work on gathering research, summarizing literature, conducting introductory analyses, and interpreting results towards a publishable research paper. 
4.	*Data collection*. During the program execution, we will collect data on student experiences, program design, and partnership needs for each one of our research questions. These will come in the form of interviews with partner faculty, interviews with external and internal students, monthly pre and post participant surveys, and reflections on program success. We detail the process below aligning it to each question.
     a.	RQ 1 “Does a cross-institutional learning community improve student efficacy and confidence in STEM learning and skills?” We will administer [monthly] follow up surveys asking students questions regarding efficacy, confidence, and anxiety surrounding data, statistics, and research [footnote on specific instruments]. In addition, at the conclusion of the year, we will interview each external student, asking questions specific to the barriers of historically underrepresented students, including belongingness, fit, and mentorship. 
     b.	RQ2: “What are the unique strengths and assets that historically underrepresented students bring to a learning community, and how can these best be engaged by the structure and approach of the learning environment?” To collect data to address this question, will use a twofold approach. First, as instructors, we will write our own notes on how the group dynamics changed and improved from past years. We will ask external students how they thought they contributed to the program with post-interviews and will additionally interview non-external students on what they thought were strengths of the QMER workshops and labs in general, as well as how working with the other students in the learning community and labs were helpful. Second, we will use insights from partner faculty and monthly survey and interview feedback from external students on which curricular approaches were most engaging and beneficial.
     c.	RQ 3 “What are the unique needs and strengths of non-research-intensive institutions creating inter-university STEM partnerships?” This is a longer-term question that we intend to make inroads on through ongoing conversations and interviews with partner faculty and departments. As part of a larger goal to construct lasting partnerships for a STEM skill transfer pipeline, we will reflect on lessons from the partnership, noting material, information, and access barriers we encountered, as well as what elements facilitated buy-in or resistance to partnership development, maintenance, and scaling. 

Through this approach, we intend to address the gaps in knowledge and procedure for supporting historically underrepresented students in developing STEM skills. Notably, while we do intend to gain insights into student needs, we take an assets-based approach to our research questions, emphasizing underrepresented student strengths and contributions over deficits [cite]. We believe assets-based approaches are more conducive to productive student development and long-term partnerships [CITE]. Additionally, we believe developing and communicating the mutual benefits of partnerships will facilitate increased buy-in to scale such programs with future grant support, as well as differentiate Auburn in terms of its approach to addressing disproportionalities in STEM student development.

While partnership development and student recruitment between institutions would face considerable barriers of distance and travel, QMER pivoted to a fully online delivery strategy during the pandemic. We only use open-source, system agnostic, and free software and data for our programs, and have developed our lessons to be fully conducted online. With a resource ecosystem built on open coding language (R, Markdown, Python), archival files formats readable by fully free, open-license software (e.g., Atom, LibreOffice, GitHub), and data built from public-use sources (e.g., Stanford Education Data Archive), students do not need institutional access, licensed software, or special permissions to fully participate. This combination of online delivery and an open-source curricular ecosystem means that we already have the capacity to scale our existing QMER learning community and labs to new students without limitations of space or resources, and can pivot if circumstances change by eliminating barriers of proximity. 

Deliverables and Benefits
As noted above, our goal is to extend our resources to foster collaborative partnerships with local colleges towards a STEM professional development pipeline to improve the strength and diversity of the STEM workforce in Alabama. We believe this produces value by aligning with the National Science Foundation’s strategic plan to “advance the national health, prosperity and welfare,” through the “development of a high-quality, diverse workforce needed to carry out the Nation’s Science, Technology, Engineering, and Mathematics (STEM) research, and building capacity for undergraduate, graduate, and post-doctoral research training” (NSF, 2018, p. 1) and support the broader University mission to “educate students and prepare them for life” and ‘drive the development of research and scholarship” through “engagement and outreach.” [CITE]. We aim to demonstrate this through specific deliverables for the purposes of (1) dissemination and (2) program expansion. 

1.	Dissemination. To disseminate the lessons of this program, we intend to report on our findings in both academic and practitioner conferences and journals. We plan to use our research findings to write and present findings on (1) asset-based techniques for learning communities to support STEM learning for non-traditional and historically underrepresented students (2) opportunities for learning communities to diversify STEM pipelines, and (3) strengths of inter-university learning community partnerships. We intend to present these findings at higher education conferences including, but not limited to: the American Association of Colleges & Universities (AAC&U) Diversity, Equity, and Student Success conference, the AAC&U Transforming STEM in Higher Education conference, and the American Educational Research Association’s (AERA) annual meeting (Division J- Postsecondary Education). Using feedback from these conferences, we intend to aim for a minimum of three publications on these findings in journals such as the Journal of Science Education and Technology, Higher Education, the Journal of Higher Education, and/or Journal for STEM Education Research. We further intend to further disseminate this information to practitioner spaces, such as writing blog posts for the American Academy for the Advancement of Science (AAAS) ARISE network, and results to local community college and HBCU partners. 	
2.	Program expansion. Our overarching goal is to use the lessons from this program to develop a scalable model that can be expanded at Auburn University to other partner institutions. If successful, this program is intended to be self-sustaining and continue on after the grant period is concluded. We see the CWSIS as an opportunity to build the crucial first step towards a broader program of combining our open-source learning community format, asset-based research, and intentional partnerships to attract and support underrepresented and under-resourced populations to STEM skills. 
However, a weakness of our current program is that the curricular model is centered around social science research and could be more strongly linked to specific STEM disciplines. To address this, we intend to use the lessons from the CWSIS research as a building block to apply for the National Science Foundation’s EHR Core Research (ECR): Building Capacity in STEM Education Research (BCSER) Grant (NSF 20-521, max amount $1m) in the ‘22-23 academic year. We intend to use the lessons from the CWSIS grant develop the capacity and curriculum to adapt the learning community to more direct STEM disciplines, specifically (1) computer science and software engineering, and (2) biosystems engineering. Our current CWSIS project is explicitly aligned to get us closer to the objectives of the NSF BCSER, by building the knowledge base, relationships, pedagogy, and evidence to expand into new fields. 
From there, we additionally hope to increase our outreach mission to engage with the social challenge of diversifying  move towards a platform for engaging K-12 teachers and administrators in learning data and analysis techniques through the QMER learning community approach by applying for the NSF INCLUDES planning grant (NSF 19-600, max amount $100,000), so that Auburn’s commitment to STEM education and will be evident in both the higher education and K-12 arenas. While the details here are still under consideration, we hope to support under-resourced (and often under-staffed) schools—such as those in the Black Belt region—with sustainable learning community partnerships and professional learning units (PLUs) to support data literacy and analysis techniques for school improvement, to eventually be part of the NSF INCLUDES network of  [Specifically, we hope to use the evidence from the current project to support and inform school development and use of ‘equity dashboards,’ and recruiting databases as a cost-neutral technique for improving underrepresented student outcomes and teacher retention.] 

We believe the overall benefits of this program will include (1) a format to learn about and address the resource and social barriers for underrepresented students; (2) a means to promote high-quality, rigorous research techniques; (3) an ongoing example asset-based learning design and research; (4) a lasting relationship with community colleges and HBCUs to improve inter-institutional learning; (5) a visible demonstration of Auburn’s commitment to social and economic improvement for all of Alabama’s citizens. 







